export {default as Welcome} from './Welcome'
export { default as AccountCreation } from './AccountCreation'
export { default as Activitys } from './Activitys'
export { default as PreChat} from './PreChat'
export { default as Chat} from './Chat'
export { default as DarkModeSwitch } from './DarkModeSwitch'
export { default as Home } from './Home'
export { default as Settings } from './Settings'
export { default as SignIn } from './SignIn'
export { default as Splash } from './Splash'

